ALTER TABLE users
ADD COLUMN IF NOT EXISTS affiliation VARCHAR(255),
ADD COLUMN IF NOT EXISTS research_interests TEXT[],
ADD COLUMN IF NOT EXISTS api_key VARCHAR(255),
ADD COLUMN IF NOT EXISTS notification_prefs JSONB DEFAULT '{}';
